import type { Metadata } from "next";
import "./globals.css";
import { montserrat } from "@/lib/fonts";
import style from './style.module.scss'
import Header from "@/containers/Header/Header";
import Image from "next/image";
import LogoHeader from '../images/logoheader.png'
import Footer from "@/containers/Footer/Footer";

export const metadata: Metadata = {
  title: "KILLA",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body
        className={`${montserrat.className}`}
      >
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
